'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Lang = 'vi' | 'en';

const T = {
  vi: {
    // ── channels page ──────────────────────────────────────────────────────
    failedToLoad: 'Không tải được danh sách tài khoản',
    connectSuccessPages: 'Kết nối thành công! Đang quét Pages và Instagram...',
    connectSuccessData: 'Kết nối thành công! Đang tải dữ liệu...',
    connectFailed: (msg: string) => `Kết nối thất bại: ${msg}`,
    scanDone: '✅ Đã quét xong tất cả Pages và Instagram!',
    popupBlocked: 'Trình duyệt chặn popup — hãy bỏ chặn popup cho trang này.',
    checkingConnection: 'Đang kiểm tra kết nối...',
    connectSuccess: 'Kết nối thành công!',
    refreshHint: 'Nhấn "Làm mới" để tải lại danh sách tài khoản.',
    connectionError: 'Lỗi kết nối',
    enterToken: 'Vui lòng nhập mã token',
    accountConnected: 'Kết nối tài khoản thành công!',
    connectionErrorWith: (msg: string) => `Kết nối lỗi: ${msg}`,
    cannotDisconnectOther: 'Bạn không thể gỡ tài khoản của người khác',
    disconnectConfirmWithPages: (name: string) =>
      `Gỡ kết nối "${name}"?\n\nTất cả Fanpage và Instagram Business liên kết sẽ bị gỡ theo.`,
    disconnectConfirm: (name: string) => `Gỡ kết nối "${name}"?`,
    disconnected: 'Đã gỡ kết nối',
    disconnectFailed: (msg: string) => `Không thể gỡ kết nối: ${msg}`,
    tabAll: 'Tất cả',
    expiringBanner: (n: number) => `${n} tài khoản sắp hết hạn token`,
    expired: 'Đã hết hạn',
    daysLeft: (n: number) => `còn ${n} ngày`,
    renewHint: 'Kết nối lại để gia hạn token và tiếp tục đăng bài.',
    channels: 'Kênh',
    manageChannels: 'Quản lý kênh',
    channelCount: (n: number) => `${n} kênh`,
    refresh: 'Làm mới',
    autoFromFB: 'Tự động lấy từ Facebook Page',
    connecting: 'Đang kết nối...',
    connectInstagram: 'Kết nối Instagram',
    addInstagram: 'Thêm Instagram',
    showN: (n: number) => `Hiện (${n})`,
    hide: 'Ẩn',
    addAccount: 'Thêm tài khoản',
    enterTokenManual: 'Nhập token thủ công',
    hideTokenForm: 'Ẩn form token',
    igBusinessCount: (n: number) => `Instagram Business (${n})`,
    showMoreAccounts: (n: number) => `Xem thêm ${n} account`,
    collapse: 'Thu gọn',
    viewAllIg: (n: number) => `Xem tất cả ${n} Instagram account`,
    expiresOn: (date: string) => `Hết hạn ${date}`,
    managedPages: (n: number) => `Các Fanpage được quản lý: (${n})`,
    showMorePages: (n: number) => `Xem thêm ${n} page`,
    viewAllPages: (n: number) => `Xem tất cả ${n} page`,
    loadThreadsToken: 'Nạp Token Threads trực tiếp',
    threadsTokenDesc:
      'Nhấp nút "Tạo mã truy cập" cho tài khoản Threads Tester trong Meta Developer Dashboard, copy mã token và dán vào đây:',
    tokenPlaceholder: 'Dán mã Token (ví dụ: TH_...)',
    save: 'Lưu',
    igAutoNote: 'Instagram Business sẽ tự động được thêm khi bạn kết nối Facebook.',
    noAccounts: (platform: string, loginLabel: string) =>
      `Chưa có tài khoản ${platform}. Nhấn "${loginLabel}" để bắt đầu.`,
    remove: 'Gỡ',
    loginLabel: {
      FACEBOOK: 'Đăng nhập với Facebook',
      INSTAGRAM: 'Kết nối Instagram',
      TIKTOK: 'Đăng nhập với TikTok',
      THREADS: 'Đăng nhập với Threads',
      YOUTUBE: 'Đăng nhập với YouTube',
      ZALO: 'Đăng nhập với Zalo',
    },
    dateLocale: 'vi',
    // ── NotificationBell ───────────────────────────────────────────────────
    notifTitle: '🔔 Thông báo đăng bài',
    markAllRead: 'Đánh dấu đã đọc',
    noNotifs: 'Chưa có thông báo',
    notifsHint: 'Thông báo sẽ hiển thị khi bạn đăng bài',
    postSuccess: 'Đăng bài thành công',
    postFailed: 'Đăng bài thất bại',
    postPending: 'Đang chờ xử lý',
    retry: 'Đăng lại',
    viewHistory: 'Xem tất cả lịch sử',
    retryQueued: 'Đã đưa vào hàng chờ đăng lại',
    retryFailed: 'Retry thất bại',
    notifTabSystem: 'Hệ thống',
    notifTabTask: 'Task',
    taskNotifEmpty: 'Chưa có thông báo task',
    taskNotifHint: 'Thông báo sẽ hiển thị khi có task mới, nộp task hoặc được duyệt',
    viewTasks: 'Xem tất cả task',
    // ── BackgroundTaskManager ──────────────────────────────────────────────
    processingTasks: (n: number) => `Đang xử lý ${n} tác vụ...`,
    allDone: 'Tất cả tác vụ hoàn tất',
    uploading: 'Đang tải lên...',
    processing: 'Đang xử lý...',
    waiting: 'Đang chờ...',
    done: 'Hoàn tất!',
    failed: 'Thất bại',
    cancelled: 'Đã hủy',
    sendingToSocial: 'Đang gửi tới MXH...',
    queuePos: (pos: number, total: number | null) =>
      total != null ? `Hàng chờ: #${pos}/${total}` : `Hàng chờ: #${pos}`,
    // ── compose/page.tsx ──────────────────────────────────────────────────
    compose: {
      breadcrumbWrite: 'Viết bài',
      breadcrumbNormalPost: 'Đăng thường',
      tabChannels: 'Kênh',
      tabEditor: 'Soạn thảo',
      tabPreview: 'Xem trước',
      topTabPublish: 'Đăng bài',
      topTabCustomize: 'Tùy chỉnh',
      topTabTopic: 'Chủ đề',
      topTabPreview: 'Xem trước',
      channelsTitle: 'Kênh đăng bài',
      postModeLabel: 'CHẾ ĐỘ ĐĂNG',
      modeText: 'Chữ',
      modeImage: 'Ảnh',
      modeVideoVertical: 'Video Dọc',
      modeVideoHorizontal: 'Video Ngang',
      searchChannelsPlaceholder: 'Tìm kiếm kênh...',
      customGroupsLabel: 'Nhóm tùy chỉnh:',
      groupNamePlaceholder: 'Tên nhóm...',
      saveGroup: '+ Lưu nhóm',
      noGroupsYet: 'Chưa có nhóm nào.',
      accountsOfPlatform: (platform: string) => `Tài khoản ${platform}`,
      igBusiness: 'IG Business',
      fanpage: 'Fanpage',
      tokenExpiresIn: (n: number) => `⚠️ Token hết hạn trong ${n} ngày`,
      noMatchingChannels: 'Không tìm thấy kênh phù hợp',
      dragToResize: 'Kéo để điều chỉnh độ rộng',
      customizePostTitle: 'Tùy chỉnh bài đăng',
      noVideoYet: 'Chưa có video',
      addVideoHintPrefix: 'Thêm video ở tab',
      addVideoHintTab: 'Đăng bài',
      addVideoHintSuffix: 'trước',
      thumbnailTitle: 'Ảnh bìa video',
      thumbnailDesc: 'Chọn frame từ video hoặc upload ảnh tùy chỉnh. Dùng cho YouTube, TikTok, Facebook video.',
      thumbnailAlt: 'Ảnh bìa',
      thumbnailSelected: 'Ảnh bìa đã chọn',
      thumbnailNotChosen: 'Chưa chọn',
      driveVideoNoLibraryId: 'Video Drive chưa có ID thư viện — thêm từ thư viện media',
      chooseFrameFromVideo: 'Chọn frame từ video',
      serverSide: '(server-side)',
      chooseImageFromLibrary: 'Chọn ảnh từ thư viện',
      removeThumbnail: 'Xoá ảnh bìa',
      tabPublishNow: 'Đăng ngay',
      tabSchedule: 'Đặt lịch',
      tabDraft: 'Lưu nháp',
      draftsButton: (n: number) => `Nháp (${n})`,
      publishNowBtn: 'Đăng ngay',
      scheduleNowBtn: 'Đặt lịch ngay',
      saveDraftBtn: 'Lưu nháp',
      scheduledTimeLabel: 'Thời gian đặt lịch đăng bài:',
      messagePlaceholder: 'Hôm nay bạn muốn chia sẻ điều gì?...',
      public: 'Công khai',
      aiOptimizing: 'Đang tối ưu...',
      aiOptimize: 'AI Tối ưu nội dung',
      overLimit: (platforms: string) => `Quá giới hạn: ${platforms}`,
      charCount: (n: number) => `${n} ký tự`,
      chooseFromLibrary: 'Chọn từ thư viện media',
      chooseUploadedFile: 'Chọn file đã upload trước',
      previewTitle: 'Xem trước bài viết',
      perPlatformToggle: '✏️ Tùy chỉnh nội dung theo từng platform',
      useCommonContent: 'Dùng nội dung chung',
      perPlatformPlaceholder: (label: string) => `Nội dung riêng cho ${label} (bỏ trống = dùng nội dung chung)`,
      selectChannelToCustomize: 'Chọn kênh để tùy chỉnh nội dung',
      postingTimeLabel: 'Thời gian đăng bài',
      privacyLabel: 'Quyền riêng tư (FB)',
      privacyPublic: '👤 Công khai',
      privacyFriends: '👥 Bạn bè',
      privacyOnlyMe: '🔒 Chỉ mình tôi',
      draftsListTitle: 'Danh sách bản nháp',
      noDraftsSaved: 'Chưa có bản nháp nào được lưu.',
      noContent: '(Không có nội dung)',
      clickToSelect: 'Nhấn để chọn →',
      hourSuffix: (h: string) => `${h} giờ`,
      minuteSuffix: (m: string) => `${m} phút`,
      beforeUnloadWarning: 'Hệ thống đang xử lý bài đăng của bạn. Bạn có chắc muốn rời đi không?',
      selectAtLeastOneChannelGroup: 'Vui lòng chọn ít nhất 1 kênh',
      groupSaved: 'Đã lưu nhóm kênh',
      enterContentFirst: 'Vui lòng nhập nội dung trước',
      aiHashtagSuggested: (count: number, source: string) => `AI gợi ý ${count} hashtag (nguồn: ${source})`,
      aiSourceAi: '🤖 AI',
      aiSourceKeyword: '🔑 Keyword',
      hashtagSuggestFailed: 'Không lấy được gợi ý hashtag, thử lại sau',
      enterContentBeforeDraft: 'Vui lòng nhập nội dung trước khi lưu nháp',
      draftSaved: 'Đã lưu nháp!',
      draftSaveFailed: 'Lưu nháp thất bại',
      selectAtLeastOneChannel: 'Vui lòng chọn ít nhất một kênh',
      enterContent: 'Vui lòng nhập nội dung',
      addAtLeastOneHashtag: '🏷️ Vui lòng thêm ít nhất 1 hashtag',
      selectScheduleTime: 'Vui lòng chọn thời gian đặt lịch',
      invalidScheduleTime: 'Thời gian đặt lịch không hợp lệ',
      scheduleTimeMustBeFuture: 'Thời gian đặt lịch phải ở tương lai',
      allScheduled: 'Đã đặt lịch tất cả!',
      someScheduleFailed: 'Một số kênh đặt lịch thất bại',
      postSuccessAll: 'Đã đăng bài thành công!',
      someFailed: 'Một số kênh đăng bài thất bại',
      addedToQueue: (n: number) => `Đã thêm ${n} bài vào hàng chờ — đang xử lý...`,
      unknownError: 'Lỗi không xác định',
      draftLoaded: 'Đã nạp bản nháp',
      thumbnailSet: 'Đã đặt ảnh bìa!',
      thumbnailAutoSet: 'Đã tự động đặt ảnh bìa từ video!',
      filesAddedFromLibrary: (n: number) => `Đã thêm ${n} file từ thư viện`,
      postingTaskName: (preview: string) => `Đăng bài: ${preview}...`,
      channelsDone: (done: number, total: number) => `Đã xong ${done}/${total} kênh`,
    },
    templateManager: {
      fillVariables: 'Điền biến động',
      enterVariable: (v: string) => `Nhập ${v}...`,
      preview: 'Xem trước',
      cancel: 'Huỷ',
      apply: 'Áp dụng',
      enterTemplateName: 'Nhập tên template',
      contentEmpty: 'Nội dung trống',
      templateSaved: (name: string) => `Đã lưu template "${name}"`,
      templateDeleted: 'Đã xoá template',
      templateApplied: (name: string) => `Đã áp dụng template "${name}"`,
      templateAppliedGeneric: 'Đã áp dụng template',
      template: 'Template',
      contentTemplate: 'Template nội dung',
      saveCurrentAsTemplate: 'Lưu nội dung hiện tại làm template',
      templateNamePlaceholder: 'Tên template (VD: Bài giới thiệu sản phẩm vàng)',
      useVariableHintPrefix: 'Dùng',
      useVariableHintSuffix: 'để tạo biến động trong nội dung',
      detectedVariables: (vars: string) => `Phát hiện biến: ${vars}`,
      saveTemplate: 'Lưu template',
      noTemplatesYet: 'Chưa có template nào',
      noTemplatesHint: 'Soạn nội dung và lưu làm template để dùng lại',
      templateListCount: (n: number) => `Danh sách template (${n})`,
      variablesLabel: (vars: string) => `Biến: ${vars}`,
      use: 'Dùng',
    },
    mediaLibrary: {
      title: 'Thư viện Media',
      statsLine: (count: number, totalMB: number) => `${count} file · ${totalMB} MB đã lưu`,
      loadFailed: 'Không tải được thư viện media',
      maxSelectReached: (max: number) => `Chỉ có thể chọn tối đa ${max} file`,
      searchPlaceholder: 'Tìm kiếm tên file...',
      filterAll: 'Tất cả',
      filterImage: 'Ảnh',
      filterVideo: 'Video',
      filterDate: 'Lọc theo ngày tải lên',
      filterAllDates: 'Xem tất cả ngày',
      fileCount: (total: number) => `${total} file`,
      uploadingFile: (index: number, total: number, isVideo: boolean, fileName: string) =>
        `[${index}/${total}] ${isVideo ? 'Đang tải lên Google Drive' : 'Đang lưu'} ${fileName}...`,
      uploadingToDrivePct: (pct: number) => `${pct}% - đang tải lên Drive...`,
      processingShort: 'Đang xử lý...',
      uploadToDrive: 'Upload vào Drive',
      unknownError: 'Lỗi không xác định',
      uploadFileFailed: (fileName: string, errorMsg: string) => `❌ Lỗi tải lên ${fileName}: ${errorMsg}`,
      uploadAllSuccess: (count: number) => `✅ Đã lưu ${count} file vào thư viện`,
      uploadPartialSuccess: (success: number, fail: number) => `⚠️ Đã tải lên ${success} file. Có ${fail} file bị lỗi (xem thông báo).`,
      uploadAllFailed: (fail: number) => `❌ Tải lên thất bại cả ${fail} file.`,
      processingError: 'Có lỗi xảy ra trong quá trình xử lý',
      noFileSelected: 'Chưa chọn file nào',
      confirmDelete: (name: string) => `Xoá "${name}" khỏi thư viện?`,
      deleted: 'Đã xoá',
      deleteFailed: 'Xoá thất bại',
      emptyTitle: 'Chưa có media nào',
      emptyNoMatch: 'Không tìm thấy file phù hợp',
      emptyHint: 'Upload ảnh hoặc video để thêm vào thư viện',
      uploadNow: 'Upload file ngay',
      videoLabel: 'Video',
      historyLoadFailed: 'Không tải được lịch sử',
      viewPostHistory: 'Xem lịch sử bài đăng',
      removeFromLibrary: 'Xóa khỏi thư viện',
      historyOf: (name: string) => `Lịch sử: ${name}`,
      loadingEllipsis: 'Đang tải…',
      noPostsUsingFile: 'Chưa có bài đăng nào dùng file này',
      postStatusSuccess: 'Thành công',
      postStatusFailed: 'Thất bại',
      postStatusPending: 'Đang chờ',
      pageOf: (page: number, pages: number) => `Trang ${page}/${pages}`,
      selectedCount: (count: number) => `Đã chọn ${count} file`,
      clickToSelect: 'Click vào file để chọn',
      deselect: 'Bỏ chọn',
      insertIntoPost: (count: number) => `Chèn ${count > 0 ? `(${count}) ` : ''}vào bài`,
    },
    videoFramePicker: {
      previewFailed: (msg: string) => `Không thể xem trước frame: ${msg}`,
      coverSetSuccess: 'Đã đặt ảnh bìa!',
      saveCoverFailed: (msg: string) => `Lưu ảnh bìa thất bại: ${msg}`,
      serverNoticePrefix: 'Video lưu trên Google Drive — frame được trích xuất qua server (FFmpeg). Nhập giây cần chọn, bấm',
      previewLabel: 'Xem trước',
      serverNoticeMiddle: 'để kiểm tra, rồi bấm',
      confirmLabel: 'Xác nhận',
      serverNoticeSuffix: '.',
      selectSecondLabel: 'Chọn giây cần lấy frame',
      secondsPlaceholder: 'giây',
      secondsFromStart: 'giây từ đầu video',
      generating: 'Đang tạo...',
      loadingFrameExtract: 'Đang tải video và trích xuất frame...',
      firstLoadHint: 'Có thể mất 15–30 giây lần đầu',
      framePreviewed: 'Frame đã xem trước',
      cannotLoadFrame: 'Không thể tải frame',
      enterSecondAndPreview: 'Nhập giây và bấm Xem trước',
      frameAt: (time: string) => `Frame tại ${time}`,
      noPreviewYet: 'Chưa có xem trước',
      cancel: 'Hủy',
      saving: 'Đang lưu...',
      confirmFrameAt: (time: string) => `Xác nhận frame ${time}`,
      cannotCaptureFrame: 'Không thể chụp frame. Thử kéo thanh video và thử lại.',
      videoCoverSetSuccess: 'Đã đặt ảnh bìa video!',
      saveCoverFailedShort: 'Lưu ảnh bìa thất bại',
      selectedAt: (time: string) => `Đã chọn tại ${time}`,
      generatingThumbnails: 'Đang tạo frame thumbnails...',
      sampleFramesCount: (n: number) => `${n} frame mẫu — bấm để chọn nhanh`,
      dragTimelineToSelect: 'Kéo thanh thời gian để chọn frame',
      corsRestrictionNotice: 'Video này không cho phép chụp frame trực tiếp (hạn chế CORS).',
      useLibraryButtonPrefix: 'Hãy dùng nút',
      selectFromLibraryLabel: 'Chọn từ thư viện',
      useLibraryButtonSuffix: 'để chọn ảnh bìa.',
      currentFrame: 'Frame hiện tại',
      dragToPreview: 'Kéo thanh để xem trước frame',
      useFrameAt: (time: string) => `Dùng frame ${time}`,
      thisFrame: 'này',
      pickCoverFromVideo: 'Chọn ảnh bìa từ video',
      serverExtractHint: 'Trích xuất frame qua server · Google Drive',
      dragTimelineOrQuickPick: 'Kéo thanh thời gian hoặc chọn nhanh bên dưới',
    },
    hashtagPanel: {
      title: 'Hashtag Mục tiêu *',
      addSuggestion: '+ Thêm gợi ý',
      tagNamePlaceholder: 'Tên hashtag...',
      inputPlaceholderEmpty: 'Nhập hashtag và nhấn Space...',
      inputPlaceholderMore: 'Thêm...',
      quickSuggestions: 'Gợi ý nhanh:',
    },
    platformPreview: {
      justNow: 'Vừa xong',
      like: 'Thích',
      comment: 'Bình luận',
      share: 'Chia sẻ',
      save: 'Lưu',
      commentsCount: (n: number) => `${n} bình luận`,
      sharesCount: (n: number) => `${n} lượt chia sẻ`,
      likesCount: (n: number) => `${n} lượt thích`,
      viewsCount: (n: number) => `${n} lượt xem`,
      originalAudio: 'Nhạc nền',
      videoTitlePlaceholder: 'Tiêu đề video',
    },
    publishProgress: {
      resultTitle: 'Kết quả hoàn tất',
      processingTitle: 'Đang xử lý đăng bài',
      resultSummary: (success: number, fail: number) => `${success} thành công, ${fail} lỗi`,
      doNotCloseBrowser: 'Vui lòng không đóng trình duyệt lúc này',
      channelsCount: (done: number, total: number) => `${done}/${total} kênh`,
      elapsedTime: (time: string) => `⏱ ${time}`,
      etaTime: (time: string) => `ETA ~${time}`,
      globalQueueStatus: (total: number) => `Hàng chờ hệ thống: ${total} bài đang chờ xử lý`,
      yourPostPosition: (pos: number) => ` — bài của bạn ở vị trí #${pos}`,
      postsAheadEstimate: (count: number, time: string) => `Còn ~${count} bài trước bạn • ước tính ${time}`,
      yourTurnSoon: 'Bài của bạn sắp đến lượt xử lý',
      processingPct: (pct: number) => `Đang xử lý... ${pct}%`,
      successLabel: 'Thành công ✓',
      failLabel: 'Thất bại',
      queuePositionWithAhead: (pos: number, total: number, ahead: number) => `#${pos}/${total} — còn ${ahead} bài trước`,
      queuePositionOnly: (pos: number) => `Hàng chờ #${pos}`,
      waitingLabel: 'Đang chờ xử lý...',
      confirmButton: 'Xác nhận',
    },
    bulk: {
      pageTitle: 'Đăng bài hàng loạt từ CSV',
      pageSubtitle: 'Upload file CSV để lên lịch đăng nhiều bài cùng lúc',
      downloadSample: 'Tải mẫu CSV',
      processing: 'Đang xử lý...',
      publishCount: (n: number) => `Đăng ${n} bài`,
      instructions: 'Hướng dẫn',
      colAccountName: 'Tên account đã kết nối (tìm gần đúng)',
      colContent: 'Nội dung bài đăng (đặt trong dấu " nếu có dấu phẩy)',
      colHashtags: '#Tag1 #Tag2 (tùy chọn)',
      colMediaUrl: 'Link ảnh/video public (tùy chọn)',
      colScheduledAt: 'YYYY-MM-DDTHH:mm — bỏ trống = đăng ngay vào hàng chờ',
      dropFileHere: 'Thả file vào đây',
      dragOrClickToSelect: 'Kéo thả hoặc click để chọn file CSV',
      csvOnlyUtf8: 'Chỉ chấp nhận .csv, mã hoá UTF-8',
      rowsRead: (n: number) => `${n} hàng đã đọc`,
      rowsDoneCount: (n: number) => `${n} xong`,
      rowsReadyCount: (n: number) => `${n} sẵn sàng`,
      rowsErrorCount: (n: number) => `${n} lỗi`,
      clearAll: 'Xoá tất cả',
      thStatus: 'Trạng thái',
      thAccount: 'Tài khoản',
      thContent: 'Nội dung',
      thSchedule: 'Lịch đăng',
      noContent: 'Không có nội dung',
      postNow: 'Đăng ngay',
      csvOnly: 'Chỉ chấp nhận file .csv',
      csvEmptyOrInvalid: 'File CSV trống hoặc không đúng định dạng',
      rowsHaveErrors: (n: number) => `${n} hàng có lỗi — kiểm tra lại`,
      rowsValid: (n: number) => `Đọc được ${n} hàng hợp lệ`,
      noValidRows: 'Không có hàng hợp lệ để đăng',
      publishComplete: (done: number, failed: number) => `Hoàn tất: ${done} thành công, ${failed} thất bại`,
      missingPlatform: 'Thiếu platform',
      missingContentOrMedia: 'Thiếu content hoặc media_url',
      invalidPlatform: (platform: string) => `Platform không hợp lệ: ${platform}`,
      accountNotFound: (accountName: string, platform: string) => `Không tìm thấy account "${accountName}" cho ${platform}`,
      invalidScheduledAt: 'scheduled_at không hợp lệ (dùng ISO: YYYY-MM-DDTHH:mm)',
      scheduledAtMustBeFuture: 'scheduled_at phải là thời điểm trong tương lai',
    },
    stats: {
      loadFailed: 'Không tải được dữ liệu thống kê',
      loading: 'Đang tải dữ liệu thống kê...',
      pageTitle: 'Thống kê đăng bài',
      postsInRange: (n: string | number) => `${n} bài trong khoảng đã chọn`,
      member: 'Thành viên',
      yourPosts: '(bài của bạn)',
      refresh: 'Làm mới',
      createPost: 'Đăng bài',
      range7d: '7 ngày',
      range30d: '30 ngày',
      range90d: '90 ngày',
      rangeAll: 'Tất cả',
      teamLabel: 'Team:',
      allTeams: 'Tất cả team',
      memberLabel: 'Thành viên:',
      allMembers: 'Tất cả thành viên',
      clearFilter: 'Xoá lọc',
      noDataTitle: 'Chưa có dữ liệu thống kê',
      noDataSub: 'Hãy đăng bài đầu tiên để bắt đầu thống kê',
      postNow: 'Đăng bài ngay',
      totalPosts: 'Tổng bài đăng',
      postsPerDay: (n: string | number) => `${n} bài/ngày`,
      success: 'Thành công',
      successRateSub: (n: number) => `${n}% tỉ lệ thành công`,
      failed: 'Thất bại',
      errorRateSub: (n: number) => `${n}% tỉ lệ lỗi`,
      noErrors: 'Không có lỗi',
      successRate: 'Tỉ lệ thành công',
      veryGood: '🎉 Rất tốt',
      needsImprovement: '⚠ Cần cải thiện',
      needsAttention: '❌ Cần chú ý',
      scheduled: 'Lên lịch',
      percentOfTotal: (n: number) => `${n}% tổng bài`,
      immediate: 'Đăng ngay',
      pending: 'Đang chờ',
      notProcessed: 'Chưa xử lý',
      bestPlatform: 'Platform tốt nhất',
      successRateSimple: (n: number) => `${n}% thành công`,
      notEnoughData: 'Chưa đủ dữ liệu',
      memberStatsTitle: 'Thống kê theo thành viên',
      memberStatsSummary: (count: number, total: string | number) => `${count} thành viên · ${total} bài đăng`,
      totalLabel: 'Tổng',
      trendTitle: 'Xu hướng đăng bài theo ngày',
      trendSub: (n: string | number) => `Số lượng bài mỗi ngày trong ${n} ngày qua`,
      allDaysWord: 'tất cả',
      overview: 'Tổng quan',
      postsByPlatform: 'Bài đăng theo platform',
      postsByPlatformSub: 'Phân bổ số lượng theo từng nền tảng',
      platformDetailTitle: 'Chi tiết từng platform',
      platformDetailSub: 'So sánh hiệu suất',
      noData: 'Không có dữ liệu',
      postsCount: (n: string | number) => `${n} bài`,
      hourlyTitle: 'Phân bổ theo giờ',
      hourlySub: 'Giờ cao điểm đăng bài',
      peakHour: 'giờ cao điểm',
      dowTitle: 'Phân bổ theo ngày trong tuần',
      dowSub: 'Ngày nào đăng nhiều nhất',
      peakDay: 'ngày cao điểm',
      dowLabels: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'] as string[],
      rate: 'Tỉ lệ',
      hashtagStatsTitle: 'Thống kê theo Hashtag',
      hashtagStatsSub: (n: number) => `${n} hashtag · Bấm để xem chi tiết`,
      deselect: 'Bỏ chọn',
      showMoreHashtags: (n: number) => `Xem thêm ${n} hashtag`,
      allHashtags: 'Tất cả hashtag',
      selectHashtag: 'Chọn một hashtag',
      selectHashtagHint: 'Bấm vào biểu đồ hoặc tag cloud để xem chi tiết',
      byPlatform: 'Theo platform',
      recentPosts: 'Bài đăng gần nhất',
      postTypeTitle: 'Loại đăng bài',
      postTypeSub: 'Đăng ngay vs Đặt lịch',
      postsCountWithPercent: (value: string | number, pct: number) => `${value} bài · ${pct}%`,
      recentFailuresTitle: 'Bài đăng thất bại gần đây',
      recentFailuresSub: 'Cần chú ý xử lý',
      viewAll: 'Xem tất cả →',
      noFailures: 'Không có bài thất bại!',
      noFailuresSub: 'Tuyệt vời, mọi bài đều thành công',
    },
    schedule: {
      failedToLoad: 'Không tải được danh sách lịch đăng',
      cancelConfirm: 'Huỷ bài này?',
      cancelSuccess: 'Đã huỷ',
      cancelFailed: 'Không thể huỷ',
      retryQueued: 'Đã đưa vào hàng chờ đăng lại',
      retryFailed: 'Retry thất bại',
      statusPending: 'Chờ đăng',
      statusCompleted: 'Đã đăng',
      statusFailed: 'Thất bại',
      statusCancelled: 'Đã huỷ',
      pageTitle: 'Lịch đăng bài',
      pageSubtitle: 'Quản lý các bài đăng đã lên lịch',
      viewCalendar: 'Xem lịch',
      scheduleNew: 'Lên lịch mới',
      statPending: 'Chờ đăng',
      statSuccess: 'Thành công',
      statFailed: 'Thất bại',
      emptyTitle: 'Chưa có bài nào lên lịch',
      emptyDesc: 'Tạo bài đăng và chọn thời gian đăng tự động',
      composeNow: 'Soạn bài ngay',
      groupPending: (n: number) => `Chờ đăng (${n})`,
      groupFailed: (n: number) => `Thất bại (${n})`,
      groupCompleted: (n: number) => `Đã hoàn thành (${n})`,
      groupCancelled: (n: number) => `Đã huỷ (${n})`,
      dateLocale: 'vi',
      retryingBanner: (retryCount: number) => `Đăng thất bại — đang tự động thử lại (lần ${retryCount}/3)`,
      nextRetryAt: 'Lần kế lúc',
      tokenExpiredPrefix: 'Token Facebook hết hạn/bị thu hồi —',
      reconnectAccount: 'Kết nối lại tài khoản',
      tokenExpiredSuffix: 'để tránh tiếp tục thất bại',
      tokenExpiredFailedPrefix: 'Token hết hạn —',
      reconnect: 'Kết nối lại',
      tokenExpiredFailedSuffix: 'rồi bấm thử lại',
      retryTitle: 'Thử lại',
      cancelTitle: 'Huỷ',
    },
    history: {
      activityChartTitle: 'Hoạt động 14 ngày qua',
      totalShort: 'Tổng',
      success: 'Thành công',
      dayPostsTooltip: (label: string, total: number) => `${label}: ${total} bài`,
      statusSuccess: 'Thành công',
      statusFailed: 'Thất bại',
      statusPending: 'Đang chờ',
      statusCancelled: 'Đã huỷ',
      attachedFiles: (n: number) => `${n} file đính kèm`,
      sourceScheduled: 'Lên lịch',
      sourceImmediate: 'Đăng ngay',
      copiedShort: 'Đã copy',
      repost: 'Đăng lại',
      retry: 'Thử lại',
      loadFailed: 'Không tải được lịch sử',
      copiedContent: 'Đã copy nội dung',
      retryQueued: 'Đã đưa vào hàng chờ đăng lại',
      retryFailed: 'Retry thất bại',
      repostOpening: 'Đang mở trang soạn bài với nội dung đã sao chép',
      pageTitle: 'Lịch sử đăng bài',
      pageSubtitle: 'Theo dõi tất cả các bài đã đăng',
      statsLink: 'Thống kê',
      gridViewTitle: 'Dạng lưới',
      listViewTitle: 'Dạng danh sách',
      refresh: 'Làm mới',
      newPost: 'Đăng bài mới',
      statTotal: 'Tổng bài',
      statSuccess: 'Thành công',
      statFailed: 'Thất bại',
      statPending: 'Đang chờ',
      searchPlaceholder: 'Tìm kiếm theo nội dung, tên kênh...',
      statusAll: 'Tất cả trạng thái',
      sortNewestFirst: 'Mới nhất trước',
      sortOldestFirst: 'Cũ nhất trước',
      sortNewest: 'Mới nhất',
      sortOldest: 'Cũ nhất',
      moreFilters: 'Lọc thêm',
      teamLabel: 'Team:',
      allTeams: 'Tất cả team',
      memberLabel: 'Thành viên:',
      allMembers: 'Tất cả thành viên',
      clearMemberFilter: 'Xoá lọc thành viên',
      dateFromLabel: 'Từ ngày:',
      dateToLabel: 'Đến ngày:',
      platformLabel: 'Platform:',
      allShort: 'Tất cả',
      filteringBy: 'Đang lọc:',
      clearAll: 'Xoá tất cả',
      filteredCount: (filtered: number, total: number) => `${filtered} / ${total} bài`,
      noResultsFound: 'Không tìm thấy bài nào',
      noHistoryYet: 'Chưa có lịch sử đăng bài',
      clearFilters: 'Xoá bộ lọc',
      videoThumbnailAlt: 'Video thumbnail',
      viewVideoOnDrive: 'Xem video trên Drive',
      fileNoLongerOnServer: 'File không còn trên server',
      imageNoLongerOnServer: 'Ảnh không còn trên server',
      fileCount: (n: number) => `${n} file`,
      noContent: 'Không có nội dung',
      copyContentTitle: 'Copy nội dung',
      copiedPostLink: 'Đã copy link bài đăng',
      copyPostLinkTitle: 'Copy link bài đăng',
      pageOfTotal: (page: number, totalPages: number, total: number) => `Trang ${page}/${totalPages} · ${total} bài`,
    },
    calendar: {
      statusPending: 'Chờ đăng',
      statusCompleted: 'Đã đăng',
      statusFailed: 'Thất bại',
      statusCancelled: 'Đã huỷ',
      weekdays: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'] as string[],
      months: ['Tháng 1','Tháng 2','Tháng 3','Tháng 4','Tháng 5','Tháng 6',
               'Tháng 7','Tháng 8','Tháng 9','Tháng 10','Tháng 11','Tháng 12'] as string[],
      failedToLoadSchedule: 'Không tải được lịch đăng',
      cancelPostConfirm: 'Huỷ bài này?',
      cancelled: 'Đã huỷ',
      cancelFailed: 'Không thể huỷ',
      retryQueued: 'Đã đưa vào hàng chờ đăng lại',
      retryFailed: 'Retry thất bại',
      today: 'Hôm nay',
      pendingCount: (n: number) => `${n} chờ`,
      completedCount: (n: number) => `${n} đã đăng`,
      failedCount: (n: number) => `${n} lỗi`,
      scheduleNew: 'Lên lịch mới',
      morePosts: (n: number) => `+${n} bài khác`,
      noPostsThisDay: 'Không có bài nào',
      postCount: (n: number) => `${n} bài đăng`,
      noScheduledPostsThisDay: 'Ngày này chưa có bài lên lịch',
      addPost: 'Thêm bài',
      retrying: 'Đang xử lý...',
      retry: 'Thử lại',
      cancelling: 'Đang huỷ...',
      cancelPost: 'Huỷ bài',
    },

    // ── landing page (trang bìa) ─────────────────────────────────────────────
    landing: {
      navHome: 'Trang chủ',
      navFeatures: 'Tính năng',
      navPricing: 'Bảng giá',
      login: 'Đăng nhập',
      goToDashboard: 'Vào Dashboard',
      loading: 'Đang tải...',
      badge: 'Video Intelligence Platform',
      heroTitle1: 'Tự động hóa',
      heroTitle2: 'Sáng tạo Video & AI',
      heroDesc:
        'Giải pháp toàn diện giúp bạn khám phá xu hướng TikTok/Reels, tự động tải xuống hàng loạt và phân tích chiến lược của đối thủ cạnh tranh với sức mạnh của AI.',
      checkRealtime: 'Phân tích Video Real-time',
      checkUnlimited: 'Không giới hạn kênh',
      partnersTitle: 'ĐƯỢC HỖ TRỢ BỞI CÁC NỀN TẢNG HÀNG ĐẦU',
      coreTechTitle: 'Công nghệ lõi của chúng tôi',
      coreTechDesc: 'Hệ thống phân tích video thông minh được xây dựng trên nền tảng Big Data và AI tiên tiến nhất.',
      feature1Title: 'Scraping Thông minh',
      feature1Desc: 'Tự động thu thập dữ liệu video, bình luận và xu hướng từ TikTok/Instagram theo thời gian thực.',
      feature2Title: 'Dự báo Xu hướng',
      feature2Desc: 'Sử dụng AI để phân tích và dự đoán các trào lưu nội dung viral tiếp theo.',
      feature3Title: 'Quản lý Đa kênh',
      feature3Desc: 'Tập trung quản lý hàng trăm kênh video trên một bảng điều khiển duy nhất.',
    },

    // ── login page ───────────────────────────────────────────────────────────
    login: {
      brandTagline: 'Video Intelligence Platform',
      title: 'Đăng nhập tài khoản',
      subtitle: 'Nhập thông tin của bạn để truy cập hệ thống',
      emailLabel: 'Email',
      emailInvalid: 'Email không hợp lệ',
      passwordLabel: 'Mật khẩu',
      passwordMin: 'Mật khẩu phải có ít nhất 8 ký tự',
      forgotPassword: 'Quên mật khẩu?',
      submit: 'Đăng nhập',
      or: 'Hoặc',
      continueWithGoogle: 'Tiếp tục với Google',
      noAccount: 'Chưa có tài khoản? Liên hệ Leader/Admin để được cấp quyền truy cập.',
    },

    // ── điều hướng chung (header, mobile drawer) ─────────────────────────────
    nav: {
      menuSocial: 'Đăng bài MXH',
      menuDiscovery: 'Khám phá Video',
      menuTasks: 'Nhiệm vụ',
      menuUtilities: 'Tiện ích',

      secOverview: 'TỔNG QUAN',
      secDailyReport: 'BÁO CÁO HÀNG NGÀY',
      secChannel: 'KÊNH',
      secManagement: 'QUẢN LÝ',
      secAccount: 'TÀI KHOẢN',
      secPublish: 'ĐĂNG BÀI',
      secStats: 'THỐNG KÊ',
      secAnalysis: 'PHÂN TÍCH',
      secDiscover: 'KHÁM PHÁ',
      secCollections: 'BỘ SƯU TẬP',
      secTasks: 'NHIỆM VỤ',
      secTeamCatalog: 'ĐỘI NHÓM & DANH MỤC',
      secPersonal: 'CÁ NHÂN',
      secAiVoice: 'GIỌNG NÓI AI',
      secDownloadTools: 'CÔNG CỤ TẢI VIDEO',

      dashboardAdmin: 'Dashboard Admin',
      dashboardAdminDesc: 'Biểu đồ tổng quan toàn hệ thống',
      dashboardLeader: 'Dashboard Leader',
      dashboardLeaderDesc: 'Biểu đồ theo góc nhìn Leader',
      performance: 'Hiệu suất',
      performanceDesc: 'Theo dõi KPI & hiệu suất cá nhân',
      teamOverview: 'Tổng quan nhóm',
      teamOverviewDesc: 'Dashboard analytics toàn nhóm',
      dashboardMain: 'Dashboard Tổng',
      dashboardMainDesc: 'Bảng điều khiển quản lý hệ thống',
      ranking: 'Bảng xếp hạng',
      rankingDesc: 'Xếp hạng thành viên trong tháng',
      personalProgress: 'Tiến độ cá nhân',
      personalProgressDesc: 'Lịch sử & biểu đồ tiến độ cá nhân',

      report: 'Báo cáo',
      reportDesc: 'Báo cáo ngày & tháng của Leader / Member',
      reportTraffic: 'Báo cáo traffic',
      reportTrafficDesc: 'Thống kê lượt xem, click, nguồn traffic theo ngày',
      reportTrafficCta: 'Xem báo cáo',
      todayTasks: 'Công việc hôm nay',
      todayTasksDesc: 'Danh sách task & tiến độ trong ngày của member',
      todayTasksCta: 'Xem công việc',
      monthlyReport: 'Báo cáo tháng',
      monthlyReportDesc: 'Tổng hợp hiệu suất, traffic và doanh thu theo tháng',
      monthlyReportCta: 'Xem báo cáo tháng',
      checklistView: 'Xem báo cáo',
      checklistViewDesc: 'Xem báo cáo, checklist và phê duyệt trong hệ thống',
      checklist: 'Checklist',
      checklistDesc: 'Danh sách công việc cần hoàn thành hôm nay',
      outstandingApprove: 'Duyệt vấn đề & win',
      outstandingApproveDesc: 'Duyệt và ghi nhận vấn đề nổi bật & thành tích ngày',
      outstanding: 'Vấn đề & Win',
      outstandingDesc: 'Ghi nhận vấn đề nổi bật & thành tích ngày',

      myChannels: 'Kênh của tôi',
      myChannelsDesc: 'Danh sách kênh MXH của bạn',
      teamChannels: 'Quản lý kênh nhóm',
      teamChannelsDesc: 'Danh sách kênh MXH của toàn team',
      hr: 'Quản lý nhân sự',
      hrDesc: 'Thêm, sửa, xóa nhân sự trong team',

      connectAccounts: 'Kết nối tài khoản',
      connectAccountsDesc: 'Kết nối Facebook, Instagram, TikTok, Threads, YouTube, Zalo',
      compose: 'Soạn & đăng bài',
      composeDesc: 'Tạo và đăng bài lên nhiều nền tảng',
      schedule: 'Lịch đăng',
      scheduleDesc: 'Quản lý bài đăng theo lịch tự động',
      monthCalendar: 'Lịch tháng',
      monthCalendarDesc: 'Xem bài đặt lịch dạng calendar theo tháng',
      postHistory: 'Lịch sử đăng',
      postHistoryDesc: 'Theo dõi toàn bộ lịch sử bài đã đăng',
      socialStats: 'Thống kê',
      socialStatsDesc: 'Biểu đồ & phân tích hiệu suất đăng bài',

      channels: 'Channels',
      channelsDesc: 'Quản lý kênh mạng xã hội',
      channelAnalysis: 'Phân tích kênh',
      channelAnalysisDesc: 'Phân tích sâu dữ liệu kênh',
      searchHub: 'Tìm kiếm Video (Hub)',
      searchHubDesc: 'Tìm kiếm video trên toàn nền tảng',
      collections: 'Bộ sưu tập',
      collectionsDesc: 'Video hay do Leader & Manager tuyển chọn cho team',
      translateContent: 'Dịch Content',
      translateContentDesc: 'Dịch content có sẵn và recheck bằng bảng 3 cột',

      taskOverview: 'Tổng quan',
      taskOverviewDesc: 'Dashboard tổng quan hệ thống nhiệm vụ',
      taskList: 'Danh sách nhiệm vụ',
      taskListDesc: 'Xem và quản lý toàn bộ nhiệm vụ',
      teams: 'Đội nhóm',
      teamsDesc: 'Quản lý team, kho sản phẩm & source của team',
      catalog: 'Danh mục tổng',
      catalogDesc: 'Kho sản phẩm, content, source toàn hệ thống',
      myCatalog: 'Kho cá nhân',
      myCatalogDesc: 'Sản phẩm, content, source của bạn',
      kpi: 'KPI',
      kpiDesc: 'Theo dõi chỉ số KPI cá nhân',
      taskSettings: 'Cài đặt',
      taskSettingsDesc: 'Cấu hình tự động hóa & phân công nhiệm vụ',

      aiOverview: 'Tổng quan',
      aiOverviewDesc: 'Xem báo cáo chi tiêu, token tiêu thụ & số lượng voice',
      cloneVoice: 'Clone Voice',
      cloneVoiceDesc: 'Clone & tạo giọng nói AI từ văn bản, dịch kịch bản',

      videoDownloader: 'Tải video MXH',
      videoDownloaderDesc: 'Tải MP4/MP3 từ YouTube, TikTok, Facebook... kèm Chrome extension',

      contentReport: 'Báo cáo content',
      systemSettings: 'Cài đặt hệ thống',
      settings: 'Cài đặt',
      logout: 'Đăng xuất',
      reportPanelTitle: 'Báo cáo',
      reportPanelDesc: 'Báo cáo hiệu suất cho Leader & Member',
      themeToLight: 'Chuyển sang giao diện sáng',
      themeToDark: 'Chuyển sang giao diện tối',

      roleAdmin: 'Quản trị viên',
      roleManager: 'Quản lý',
      roleLeader: 'Trưởng nhóm',
      roleMember: 'Thành viên',
      roleEditor: 'Editor',
      roleContent: 'Content',
    },
  },
  en: {
    failedToLoad: 'Failed to load accounts',
    connectSuccessPages: 'Connected! Scanning Pages and Instagram...',
    connectSuccessData: 'Connected! Loading data...',
    connectFailed: (msg: string) => `Connection failed: ${msg}`,
    scanDone: '✅ All Pages and Instagram accounts scanned!',
    popupBlocked: 'Browser blocked popup — please allow popups for this site.',
    checkingConnection: 'Checking connection...',
    connectSuccess: 'Connected successfully!',
    refreshHint: 'Click "Refresh" to reload the account list.',
    connectionError: 'Connection error',
    enterToken: 'Please enter a token',
    accountConnected: 'Account connected successfully!',
    connectionErrorWith: (msg: string) => `Connection error: ${msg}`,
    cannotDisconnectOther: "You cannot disconnect other users' accounts",
    disconnectConfirmWithPages: (name: string) =>
      `Disconnect "${name}"?\n\nAll linked Fanpages and Instagram Business accounts will also be disconnected.`,
    disconnectConfirm: (name: string) => `Disconnect "${name}"?`,
    disconnected: 'Disconnected',
    disconnectFailed: (msg: string) => `Failed to disconnect: ${msg}`,
    tabAll: 'All',
    expiringBanner: (n: number) => `${n} account${n > 1 ? 's' : ''} with expiring tokens`,
    expired: 'Expired',
    daysLeft: (n: number) => `${n} day${n > 1 ? 's' : ''} left`,
    renewHint: 'Reconnect to renew token and continue posting.',
    channels: 'Channels',
    manageChannels: 'Manage Channels',
    channelCount: (n: number) => `${n} channel${n > 1 ? 's' : ''}`,
    refresh: 'Refresh',
    autoFromFB: 'Auto-fetched from Facebook Pages',
    connecting: 'Connecting...',
    connectInstagram: 'Connect Instagram',
    addInstagram: 'Add Instagram',
    showN: (n: number) => `Show (${n})`,
    hide: 'Hide',
    addAccount: 'Add Account',
    enterTokenManual: 'Enter token manually',
    hideTokenForm: 'Hide token form',
    igBusinessCount: (n: number) => `Instagram Business (${n})`,
    showMoreAccounts: (n: number) => `Show ${n} more`,
    collapse: 'Collapse',
    viewAllIg: (n: number) => `View all ${n} Instagram account${n > 1 ? 's' : ''}`,
    expiresOn: (date: string) => `Expires ${date}`,
    managedPages: (n: number) => `Managed Fanpages: (${n})`,
    showMorePages: (n: number) => `Show ${n} more`,
    viewAllPages: (n: number) => `View all ${n} page${n > 1 ? 's' : ''}`,
    loadThreadsToken: 'Load Threads Token Directly',
    threadsTokenDesc:
      'Click the "Create Access Token" button for your Threads Tester account in Meta Developer Dashboard, copy the token and paste it here:',
    tokenPlaceholder: 'Paste Token (e.g., TH_...)',
    save: 'Save',
    igAutoNote: 'Instagram Business will be automatically added when you connect Facebook.',
    noAccounts: (platform: string, loginLabel: string) =>
      `No ${platform} accounts yet. Click "${loginLabel}" to get started.`,
    remove: 'Remove',
    loginLabel: {
      FACEBOOK: 'Login with Facebook',
      INSTAGRAM: 'Connect Instagram',
      TIKTOK: 'Login with TikTok',
      THREADS: 'Login with Threads',
      YOUTUBE: 'Login with YouTube',
      ZALO: 'Login with Zalo',
    },
    dateLocale: 'en-US',
    notifTitle: '🔔 Post Notifications',
    markAllRead: 'Mark all read',
    noNotifs: 'No notifications',
    notifsHint: 'Notifications will appear when you post',
    postSuccess: 'Post successful',
    postFailed: 'Post failed',
    postPending: 'Pending',
    retry: 'Retry',
    viewHistory: 'View all history',
    retryQueued: 'Queued for retry',
    retryFailed: 'Retry failed',
    notifTabSystem: 'System',
    notifTabTask: 'Tasks',
    taskNotifEmpty: 'No task notifications',
    taskNotifHint: 'Notifications will appear when tasks are assigned, submitted, or reviewed',
    viewTasks: 'View all tasks',
    processingTasks: (n: number) => `Processing ${n} task${n > 1 ? 's' : ''}...`,
    allDone: 'All tasks complete',
    uploading: 'Uploading...',
    processing: 'Processing...',
    waiting: 'Waiting...',
    done: 'Done!',
    failed: 'Failed',
    cancelled: 'Cancelled',
    sendingToSocial: 'Sending to social media...',
    queuePos: (pos: number, total: number | null) =>
      total != null ? `Queue: #${pos}/${total}` : `Queue: #${pos}`,
    compose: {
      breadcrumbWrite: 'Write Post',
      breadcrumbNormalPost: 'Normal Post',
      tabChannels: 'Channels',
      tabEditor: 'Editor',
      tabPreview: 'Preview',
      topTabPublish: 'Publish',
      topTabCustomize: 'Customize',
      topTabTopic: 'Topic',
      topTabPreview: 'Preview',
      channelsTitle: 'Posting Channels',
      postModeLabel: 'POST MODE',
      modeText: 'Text',
      modeImage: 'Image',
      modeVideoVertical: 'Vertical Video',
      modeVideoHorizontal: 'Horizontal Video',
      searchChannelsPlaceholder: 'Search channels...',
      customGroupsLabel: 'Custom groups:',
      groupNamePlaceholder: 'Group name...',
      saveGroup: '+ Save group',
      noGroupsYet: 'No groups yet.',
      accountsOfPlatform: (platform: string) => `${platform} accounts`,
      igBusiness: 'IG Business',
      fanpage: 'Fanpage',
      tokenExpiresIn: (n: number) => `⚠️ Token expires in ${n} day${n > 1 ? 's' : ''}`,
      noMatchingChannels: 'No matching channels found',
      dragToResize: 'Drag to resize',
      customizePostTitle: 'Customize Post',
      noVideoYet: 'No video yet',
      addVideoHintPrefix: 'Add a video in the',
      addVideoHintTab: 'Publish',
      addVideoHintSuffix: 'tab first',
      thumbnailTitle: 'Video Thumbnail',
      thumbnailDesc: 'Pick a frame from the video or upload a custom image. Used for YouTube, TikTok, Facebook video.',
      thumbnailAlt: 'Thumbnail',
      thumbnailSelected: 'Thumbnail selected',
      thumbnailNotChosen: 'Not chosen',
      driveVideoNoLibraryId: 'Drive video has no library ID yet — add it from the media library',
      chooseFrameFromVideo: 'Pick a frame from video',
      serverSide: '(server-side)',
      chooseImageFromLibrary: 'Choose image from library',
      removeThumbnail: 'Remove thumbnail',
      tabPublishNow: 'Publish Now',
      tabSchedule: 'Schedule',
      tabDraft: 'Save Draft',
      draftsButton: (n: number) => `Drafts (${n})`,
      publishNowBtn: 'Publish Now',
      scheduleNowBtn: 'Schedule Now',
      saveDraftBtn: 'Save Draft',
      scheduledTimeLabel: 'Scheduled posting time:',
      messagePlaceholder: "What would you like to share today?...",
      public: 'Public',
      aiOptimizing: 'Optimizing...',
      aiOptimize: 'AI Optimize Content',
      overLimit: (platforms: string) => `Over limit: ${platforms}`,
      charCount: (n: number) => `${n} characters`,
      chooseFromLibrary: 'Choose from media library',
      chooseUploadedFile: 'Choose a previously uploaded file',
      previewTitle: 'Post Preview',
      perPlatformToggle: '✏️ Customize content per platform',
      useCommonContent: 'Using common content',
      perPlatformPlaceholder: (label: string) => `Custom content for ${label} (leave blank = use common content)`,
      selectChannelToCustomize: 'Select a channel to customize content',
      postingTimeLabel: 'Posting Time',
      privacyLabel: 'Privacy (FB)',
      privacyPublic: '👤 Public',
      privacyFriends: '👥 Friends',
      privacyOnlyMe: '🔒 Only me',
      draftsListTitle: 'Drafts List',
      noDraftsSaved: 'No drafts saved yet.',
      noContent: '(No content)',
      clickToSelect: 'Click to select →',
      hourSuffix: (h: string) => h,
      minuteSuffix: (m: string) => m,
      beforeUnloadWarning: 'Your post is still being processed. Are you sure you want to leave?',
      selectAtLeastOneChannelGroup: 'Please select at least 1 channel',
      groupSaved: 'Group saved',
      enterContentFirst: 'Please enter content first',
      aiHashtagSuggested: (count: number, source: string) => `AI suggested ${count} hashtag${count > 1 ? 's' : ''} (source: ${source})`,
      aiSourceAi: '🤖 AI',
      aiSourceKeyword: '🔑 Keyword',
      hashtagSuggestFailed: 'Could not get hashtag suggestions, try again later',
      enterContentBeforeDraft: 'Please enter content before saving draft',
      draftSaved: 'Draft saved!',
      draftSaveFailed: 'Failed to save draft',
      selectAtLeastOneChannel: 'Please select at least one channel',
      enterContent: 'Please enter content',
      addAtLeastOneHashtag: '🏷️ Please add at least 1 hashtag',
      selectScheduleTime: 'Please select a schedule time',
      invalidScheduleTime: 'Invalid schedule time',
      scheduleTimeMustBeFuture: 'Schedule time must be in the future',
      allScheduled: 'All scheduled!',
      someScheduleFailed: 'Some channels failed to schedule',
      postSuccessAll: 'Posted successfully!',
      someFailed: 'Some channels failed to post',
      addedToQueue: (n: number) => `Added ${n} post${n > 1 ? 's' : ''} to queue — processing...`,
      unknownError: 'Unknown error',
      draftLoaded: 'Draft loaded',
      thumbnailSet: 'Thumbnail set!',
      thumbnailAutoSet: 'Thumbnail auto-set from video!',
      filesAddedFromLibrary: (n: number) => `Added ${n} file${n > 1 ? 's' : ''} from library`,
      postingTaskName: (preview: string) => `Posting: ${preview}...`,
      channelsDone: (done: number, total: number) => `Done ${done}/${total} channels`,
    },
    templateManager: {
      fillVariables: 'Fill in variables',
      enterVariable: (v: string) => `Enter ${v}...`,
      preview: 'Preview',
      cancel: 'Cancel',
      apply: 'Apply',
      enterTemplateName: 'Enter template name',
      contentEmpty: 'Content is empty',
      templateSaved: (name: string) => `Saved template "${name}"`,
      templateDeleted: 'Template deleted',
      templateApplied: (name: string) => `Applied template "${name}"`,
      templateAppliedGeneric: 'Template applied',
      template: 'Template',
      contentTemplate: 'Content templates',
      saveCurrentAsTemplate: 'Save current content as template',
      templateNamePlaceholder: 'Template name (e.g. Gold product intro post)',
      useVariableHintPrefix: 'Use',
      useVariableHintSuffix: 'to create a dynamic variable in the content',
      detectedVariables: (vars: string) => `Detected variables: ${vars}`,
      saveTemplate: 'Save template',
      noTemplatesYet: 'No templates yet',
      noTemplatesHint: 'Write content and save it as a template to reuse later',
      templateListCount: (n: number) => `Template list (${n})`,
      variablesLabel: (vars: string) => `Variables: ${vars}`,
      use: 'Use',
    },
    mediaLibrary: {
      title: 'Media Library',
      statsLine: (count: number, totalMB: number) => `${count} files · ${totalMB} MB stored`,
      loadFailed: 'Failed to load media library',
      maxSelectReached: (max: number) => `You can select up to ${max} files only`,
      searchPlaceholder: 'Search by file name...',
      filterAll: 'All',
      filterImage: 'Image',
      filterVideo: 'Video',
      filterDate: 'Filter by upload date',
      filterAllDates: 'Show all dates',
      fileCount: (total: number) => `${total} files`,
      uploadingFile: (index: number, total: number, isVideo: boolean, fileName: string) =>
        `[${index}/${total}] ${isVideo ? 'Uploading to Google Drive' : 'Saving'} ${fileName}...`,
      uploadingToDrivePct: (pct: number) => `${pct}% - uploading to Drive...`,
      processingShort: 'Processing...',
      uploadToDrive: 'Upload to Drive',
      unknownError: 'Unknown error',
      uploadFileFailed: (fileName: string, errorMsg: string) => `❌ Failed to upload ${fileName}: ${errorMsg}`,
      uploadAllSuccess: (count: number) => `✅ Saved ${count} files to the library`,
      uploadPartialSuccess: (success: number, fail: number) => `⚠️ Uploaded ${success} files. ${fail} file(s) failed (see notification).`,
      uploadAllFailed: (fail: number) => `❌ Upload failed for all ${fail} file(s).`,
      processingError: 'An error occurred during processing',
      noFileSelected: 'No file selected',
      confirmDelete: (name: string) => `Delete "${name}" from the library?`,
      deleted: 'Deleted',
      deleteFailed: 'Delete failed',
      emptyTitle: 'No media yet',
      emptyNoMatch: 'No matching files found',
      emptyHint: 'Upload images or videos to add them to the library',
      uploadNow: 'Upload file now',
      videoLabel: 'Video',
      historyLoadFailed: 'Failed to load history',
      viewPostHistory: 'View post history',
      removeFromLibrary: 'Remove from library',
      historyOf: (name: string) => `History: ${name}`,
      loadingEllipsis: 'Loading…',
      noPostsUsingFile: 'No posts use this file yet',
      postStatusSuccess: 'Success',
      postStatusFailed: 'Failed',
      postStatusPending: 'Pending',
      pageOf: (page: number, pages: number) => `Page ${page}/${pages}`,
      selectedCount: (count: number) => `${count} file(s) selected`,
      clickToSelect: 'Click a file to select it',
      deselect: 'Deselect',
      insertIntoPost: (count: number) => `Insert ${count > 0 ? `(${count}) ` : ''}into post`,
    },
    videoFramePicker: {
      previewFailed: (msg: string) => `Could not preview frame: ${msg}`,
      coverSetSuccess: 'Cover image set!',
      saveCoverFailed: (msg: string) => `Failed to save cover: ${msg}`,
      serverNoticePrefix: 'Video is stored on Google Drive — frames are extracted via server (FFmpeg). Enter the second you want, click',
      previewLabel: 'Preview',
      serverNoticeMiddle: 'to check, then click',
      confirmLabel: 'Confirm',
      serverNoticeSuffix: '.',
      selectSecondLabel: 'Select the second to grab a frame',
      secondsPlaceholder: 'seconds',
      secondsFromStart: 'seconds from start of video',
      generating: 'Generating...',
      loadingFrameExtract: 'Loading video and extracting frame...',
      firstLoadHint: 'May take 15–30 seconds the first time',
      framePreviewed: 'Frame previewed',
      cannotLoadFrame: 'Could not load frame',
      enterSecondAndPreview: 'Enter a second and click Preview',
      frameAt: (time: string) => `Frame at ${time}`,
      noPreviewYet: 'No preview yet',
      cancel: 'Cancel',
      saving: 'Saving...',
      confirmFrameAt: (time: string) => `Confirm frame ${time}`,
      cannotCaptureFrame: 'Could not capture frame. Try dragging the video timeline and try again.',
      videoCoverSetSuccess: 'Video cover image set!',
      saveCoverFailedShort: 'Failed to save cover image',
      selectedAt: (time: string) => `Selected at ${time}`,
      generatingThumbnails: 'Generating frame thumbnails...',
      sampleFramesCount: (n: number) => `${n} sample frames — click to quick-select`,
      dragTimelineToSelect: 'Drag the timeline to select a frame',
      corsRestrictionNotice: 'This video does not allow direct frame capture (CORS restriction).',
      useLibraryButtonPrefix: 'Please use the',
      selectFromLibraryLabel: 'Choose from library',
      useLibraryButtonSuffix: 'button to pick a cover image.',
      currentFrame: 'Current frame',
      dragToPreview: 'Drag the timeline to preview a frame',
      useFrameAt: (time: string) => `Use frame ${time}`,
      thisFrame: 'this',
      pickCoverFromVideo: 'Pick cover image from video',
      serverExtractHint: 'Extracting frame via server · Google Drive',
      dragTimelineOrQuickPick: 'Drag the timeline or quick-pick below',
    },
    hashtagPanel: {
      title: 'Target Hashtags *',
      addSuggestion: '+ Add suggestion',
      tagNamePlaceholder: 'Hashtag name...',
      inputPlaceholderEmpty: 'Type a hashtag and press Space...',
      inputPlaceholderMore: 'Add...',
      quickSuggestions: 'Quick suggestions:',
    },
    platformPreview: {
      justNow: 'Just now',
      like: 'Like',
      comment: 'Comment',
      share: 'Share',
      save: 'Save',
      commentsCount: (n: number) => `${n} comments`,
      sharesCount: (n: number) => `${n} shares`,
      likesCount: (n: number) => `${n} likes`,
      viewsCount: (n: number) => `${n} views`,
      originalAudio: 'Original audio',
      videoTitlePlaceholder: 'Video title',
    },
    publishProgress: {
      resultTitle: 'Completed Results',
      processingTitle: 'Publishing in Progress',
      resultSummary: (success: number, fail: number) => `${success} succeeded, ${fail} failed`,
      doNotCloseBrowser: 'Please do not close the browser at this time',
      channelsCount: (done: number, total: number) => `${done}/${total} channels`,
      elapsedTime: (time: string) => `⏱ ${time}`,
      etaTime: (time: string) => `ETA ~${time}`,
      globalQueueStatus: (total: number) => `System queue: ${total} posts waiting`,
      yourPostPosition: (pos: number) => ` — your post is at position #${pos}`,
      postsAheadEstimate: (count: number, time: string) => `~${count} posts ahead of you • estimated ${time}`,
      yourTurnSoon: 'Your post is about to be processed',
      processingPct: (pct: number) => `Processing... ${pct}%`,
      successLabel: 'Success ✓',
      failLabel: 'Failed',
      queuePositionWithAhead: (pos: number, total: number, ahead: number) => `#${pos}/${total} — ${ahead} ahead`,
      queuePositionOnly: (pos: number) => `Queue #${pos}`,
      waitingLabel: 'Waiting...',
      confirmButton: 'Confirm',
    },
    bulk: {
      pageTitle: 'Bulk Post from CSV',
      pageSubtitle: 'Upload a CSV file to schedule multiple posts at once',
      downloadSample: 'Download Sample CSV',
      processing: 'Processing...',
      publishCount: (n: number) => `Publish ${n} posts`,
      instructions: 'Instructions',
      colAccountName: 'Name of connected account (fuzzy match)',
      colContent: 'Post content (wrap in " if it contains commas)',
      colHashtags: '#Tag1 #Tag2 (optional)',
      colMediaUrl: 'Public image/video link (optional)',
      colScheduledAt: 'YYYY-MM-DDTHH:mm — leave blank = post immediately to queue',
      dropFileHere: 'Drop file here',
      dragOrClickToSelect: 'Drag and drop or click to select a CSV file',
      csvOnlyUtf8: 'Only .csv files accepted, UTF-8 encoding',
      rowsRead: (n: number) => `${n} rows read`,
      rowsDoneCount: (n: number) => `${n} done`,
      rowsReadyCount: (n: number) => `${n} ready`,
      rowsErrorCount: (n: number) => `${n} errors`,
      clearAll: 'Clear all',
      thStatus: 'Status',
      thAccount: 'Account',
      thContent: 'Content',
      thSchedule: 'Schedule',
      noContent: 'No content',
      postNow: 'Post now',
      csvOnly: 'Only .csv files are accepted',
      csvEmptyOrInvalid: 'CSV file is empty or has an invalid format',
      rowsHaveErrors: (n: number) => `${n} rows have errors — please check`,
      rowsValid: (n: number) => `Read ${n} valid rows`,
      noValidRows: 'No valid rows to publish',
      publishComplete: (done: number, failed: number) => `Done: ${done} succeeded, ${failed} failed`,
      missingPlatform: 'Missing platform',
      missingContentOrMedia: 'Missing content or media_url',
      invalidPlatform: (platform: string) => `Invalid platform: ${platform}`,
      accountNotFound: (accountName: string, platform: string) => `Account "${accountName}" not found for ${platform}`,
      invalidScheduledAt: 'Invalid scheduled_at (use ISO: YYYY-MM-DDTHH:mm)',
      scheduledAtMustBeFuture: 'scheduled_at must be a time in the future',
    },
    stats: {
      loadFailed: 'Failed to load statistics data',
      loading: 'Loading statistics...',
      pageTitle: 'Post Statistics',
      postsInRange: (n: string | number) => `${n} posts in selected range`,
      member: 'Member',
      yourPosts: '(your posts)',
      refresh: 'Refresh',
      createPost: 'New Post',
      range7d: '7 days',
      range30d: '30 days',
      range90d: '90 days',
      rangeAll: 'All',
      teamLabel: 'Team:',
      allTeams: 'All teams',
      memberLabel: 'Member:',
      allMembers: 'All members',
      clearFilter: 'Clear filter',
      noDataTitle: 'No statistics data yet',
      noDataSub: 'Create your first post to start tracking stats',
      postNow: 'Post now',
      totalPosts: 'Total posts',
      postsPerDay: (n: string | number) => `${n} posts/day`,
      success: 'Success',
      successRateSub: (n: number) => `${n}% success rate`,
      failed: 'Failed',
      errorRateSub: (n: number) => `${n}% error rate`,
      noErrors: 'No errors',
      successRate: 'Success rate',
      veryGood: '🎉 Great',
      needsImprovement: '⚠ Needs improvement',
      needsAttention: '❌ Needs attention',
      scheduled: 'Scheduled',
      percentOfTotal: (n: number) => `${n}% of total posts`,
      immediate: 'Post now',
      pending: 'Pending',
      notProcessed: 'Not processed yet',
      bestPlatform: 'Best platform',
      successRateSimple: (n: number) => `${n}% success`,
      notEnoughData: 'Not enough data',
      memberStatsTitle: 'Statistics by member',
      memberStatsSummary: (count: number, total: string | number) => `${count} members · ${total} posts`,
      totalLabel: 'Total',
      trendTitle: 'Posting trend by day',
      trendSub: (n: string | number) => `Number of posts per day over the last ${n} days`,
      allDaysWord: 'all',
      overview: 'Overview',
      postsByPlatform: 'Posts by platform',
      postsByPlatformSub: 'Distribution of post count by platform',
      platformDetailTitle: 'Platform details',
      platformDetailSub: 'Performance comparison',
      noData: 'No data',
      postsCount: (n: string | number) => `${n} posts`,
      hourlyTitle: 'Distribution by hour',
      hourlySub: 'Peak posting hours',
      peakHour: 'peak hour',
      dowTitle: 'Distribution by day of week',
      dowSub: 'Which day has the most posts',
      peakDay: 'peak day',
      dowLabels: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as string[],
      rate: 'Rate',
      hashtagStatsTitle: 'Hashtag statistics',
      hashtagStatsSub: (n: number) => `${n} hashtags · Click for details`,
      deselect: 'Deselect',
      showMoreHashtags: (n: number) => `Show ${n} more hashtags`,
      allHashtags: 'All hashtags',
      selectHashtag: 'Select a hashtag',
      selectHashtagHint: 'Click on the chart or tag cloud to view details',
      byPlatform: 'By platform',
      recentPosts: 'Recent posts',
      postTypeTitle: 'Post type',
      postTypeSub: 'Immediate vs Scheduled',
      postsCountWithPercent: (value: string | number, pct: number) => `${value} posts · ${pct}%`,
      recentFailuresTitle: 'Recent failed posts',
      recentFailuresSub: 'Needs attention',
      viewAll: 'View all →',
      noFailures: 'No failed posts!',
      noFailuresSub: 'Great job, every post succeeded',
    },
    schedule: {
      failedToLoad: 'Failed to load schedule list',
      cancelConfirm: 'Cancel this post?',
      cancelSuccess: 'Cancelled',
      cancelFailed: 'Failed to cancel',
      retryQueued: 'Queued for retry',
      retryFailed: 'Retry failed',
      statusPending: 'Pending',
      statusCompleted: 'Posted',
      statusFailed: 'Failed',
      statusCancelled: 'Cancelled',
      pageTitle: 'Post Schedule',
      pageSubtitle: 'Manage your scheduled posts',
      viewCalendar: 'View Calendar',
      scheduleNew: 'New Schedule',
      statPending: 'Pending',
      statSuccess: 'Success',
      statFailed: 'Failed',
      emptyTitle: 'No posts scheduled yet',
      emptyDesc: 'Create a post and choose an automatic posting time',
      composeNow: 'Compose Now',
      groupPending: (n: number) => `Pending (${n})`,
      groupFailed: (n: number) => `Failed (${n})`,
      groupCompleted: (n: number) => `Completed (${n})`,
      groupCancelled: (n: number) => `Cancelled (${n})`,
      dateLocale: 'en-US',
      retryingBanner: (retryCount: number) => `Post failed — automatically retrying (attempt ${retryCount}/3)`,
      nextRetryAt: 'Next attempt at',
      tokenExpiredPrefix: 'Facebook token expired/revoked —',
      reconnectAccount: 'reconnect your account',
      tokenExpiredSuffix: 'to avoid further failures',
      tokenExpiredFailedPrefix: 'Token expired —',
      reconnect: 'Reconnect',
      tokenExpiredFailedSuffix: 'then click retry',
      retryTitle: 'Retry',
      cancelTitle: 'Cancel',
    },
    history: {
      activityChartTitle: 'Activity over the last 14 days',
      totalShort: 'Total',
      success: 'Success',
      dayPostsTooltip: (label: string, total: number) => `${label}: ${total} posts`,
      statusSuccess: 'Success',
      statusFailed: 'Failed',
      statusPending: 'Pending',
      statusCancelled: 'Cancelled',
      attachedFiles: (n: number) => `${n} attached files`,
      sourceScheduled: 'Scheduled',
      sourceImmediate: 'Posted now',
      copiedShort: 'Copied',
      repost: 'Repost',
      retry: 'Retry',
      loadFailed: 'Failed to load history',
      copiedContent: 'Content copied',
      retryQueued: 'Queued for retry',
      retryFailed: 'Retry failed',
      repostOpening: 'Opening compose page with copied content',
      pageTitle: 'Posting History',
      pageSubtitle: 'Track all posts you have published',
      statsLink: 'Stats',
      gridViewTitle: 'Grid view',
      listViewTitle: 'List view',
      refresh: 'Refresh',
      newPost: 'New Post',
      statTotal: 'Total posts',
      statSuccess: 'Success',
      statFailed: 'Failed',
      statPending: 'Pending',
      searchPlaceholder: 'Search by content, channel name...',
      statusAll: 'All statuses',
      sortNewestFirst: 'Newest first',
      sortOldestFirst: 'Oldest first',
      sortNewest: 'Newest',
      sortOldest: 'Oldest',
      moreFilters: 'More filters',
      teamLabel: 'Team:',
      allTeams: 'All teams',
      memberLabel: 'Member:',
      allMembers: 'All members',
      clearMemberFilter: 'Clear member filter',
      dateFromLabel: 'From date:',
      dateToLabel: 'To date:',
      platformLabel: 'Platform:',
      allShort: 'All',
      filteringBy: 'Filtering by:',
      clearAll: 'Clear all',
      filteredCount: (filtered: number, total: number) => `${filtered} / ${total} posts`,
      noResultsFound: 'No posts found',
      noHistoryYet: 'No posting history yet',
      clearFilters: 'Clear filters',
      videoThumbnailAlt: 'Video thumbnail',
      viewVideoOnDrive: 'View video on Drive',
      fileNoLongerOnServer: 'File is no longer on the server',
      imageNoLongerOnServer: 'Image is no longer on the server',
      fileCount: (n: number) => `${n} files`,
      noContent: 'No content',
      copyContentTitle: 'Copy content',
      copiedPostLink: 'Post link copied',
      copyPostLinkTitle: 'Copy post link',
      pageOfTotal: (page: number, totalPages: number, total: number) => `Page ${page}/${totalPages} · ${total} posts`,
    },
    calendar: {
      statusPending: 'Pending',
      statusCompleted: 'Posted',
      statusFailed: 'Failed',
      statusCancelled: 'Cancelled',
      weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as string[],
      months: ['January','February','March','April','May','June',
               'July','August','September','October','November','December'] as string[],
      failedToLoadSchedule: 'Failed to load schedule',
      cancelPostConfirm: 'Cancel this post?',
      cancelled: 'Cancelled',
      cancelFailed: 'Could not cancel',
      retryQueued: 'Queued for retry',
      retryFailed: 'Retry failed',
      today: 'Today',
      pendingCount: (n: number) => `${n} pending`,
      completedCount: (n: number) => `${n} posted`,
      failedCount: (n: number) => `${n} failed`,
      scheduleNew: 'Schedule New',
      morePosts: (n: number) => `+${n} more`,
      noPostsThisDay: 'No posts',
      postCount: (n: number) => `${n} post${n > 1 ? 's' : ''}`,
      noScheduledPostsThisDay: 'No posts scheduled for this day',
      addPost: 'Add Post',
      retrying: 'Processing...',
      retry: 'Retry',
      cancelling: 'Cancelling...',
      cancelPost: 'Cancel Post',
    },

    // ── landing page ─────────────────────────────────────────────────────────
    landing: {
      navHome: 'Home',
      navFeatures: 'Features',
      navPricing: 'Pricing',
      login: 'Sign in',
      goToDashboard: 'Go to Dashboard',
      loading: 'Loading...',
      badge: 'Video Intelligence Platform',
      heroTitle1: 'Automate',
      heroTitle2: 'Video Creation & AI',
      heroDesc:
        'A comprehensive solution that helps you discover TikTok/Reels trends, bulk-download automatically, and analyze competitor strategies with the power of AI.',
      checkRealtime: 'Real-time Video Analytics',
      checkUnlimited: 'Unlimited channels',
      partnersTitle: 'POWERED BY LEADING PLATFORMS',
      coreTechTitle: 'Our Core Technology',
      coreTechDesc: 'An intelligent video analytics system built on the most advanced Big Data and AI foundations.',
      feature1Title: 'Smart Scraping',
      feature1Desc: 'Automatically collect video data, comments, and trends from TikTok/Instagram in real time.',
      feature2Title: 'Trend Forecasting',
      feature2Desc: 'Use AI to analyze and predict the next viral content waves.',
      feature3Title: 'Multi-channel Management',
      feature3Desc: 'Manage hundreds of video channels from a single dashboard.',
    },

    // ── login page ───────────────────────────────────────────────────────────
    login: {
      brandTagline: 'Video Intelligence Platform',
      title: 'Sign in to your account',
      subtitle: 'Enter your credentials to access the system',
      emailLabel: 'Email',
      emailInvalid: 'Invalid email address',
      passwordLabel: 'Password',
      passwordMin: 'Password must be at least 8 characters',
      forgotPassword: 'Forgot password?',
      submit: 'Sign in',
      or: 'Or',
      continueWithGoogle: 'Continue with Google',
      noAccount: "Don't have an account? Contact your Leader/Admin for access.",
    },

    // ── shared navigation (header, mobile drawer) ────────────────────────────
    nav: {
      menuSocial: 'Social Publishing',
      menuDiscovery: 'Video Discovery',
      menuTasks: 'Tasks',
      menuUtilities: 'Utilities',

      secOverview: 'OVERVIEW',
      secDailyReport: 'DAILY REPORTS',
      secChannel: 'CHANNELS',
      secManagement: 'MANAGEMENT',
      secAccount: 'ACCOUNTS',
      secPublish: 'PUBLISHING',
      secStats: 'STATISTICS',
      secAnalysis: 'ANALYTICS',
      secDiscover: 'DISCOVER',
      secCollections: 'COLLECTIONS',
      secTasks: 'TASKS',
      secTeamCatalog: 'TEAMS & CATALOG',
      secPersonal: 'PERSONAL',
      secAiVoice: 'AI VOICE',
      secDownloadTools: 'VIDEO DOWNLOAD TOOLS',

      dashboardAdmin: 'Admin Dashboard',
      dashboardAdminDesc: 'System-wide overview charts',
      dashboardLeader: 'Leader Dashboard',
      dashboardLeaderDesc: "Charts from the Leader's perspective",
      performance: 'Performance',
      performanceDesc: 'Track personal KPIs & performance',
      teamOverview: 'Team Overview',
      teamOverviewDesc: 'Team-wide analytics dashboard',
      dashboardMain: 'Main Dashboard',
      dashboardMainDesc: 'System management control panel',
      ranking: 'Leaderboard',
      rankingDesc: 'Member ranking for the month',
      personalProgress: 'My Progress',
      personalProgressDesc: 'Personal progress history & charts',

      report: 'Reports',
      reportDesc: 'Daily & monthly reports for Leaders / Members',
      reportTraffic: 'Traffic Report',
      reportTrafficDesc: 'Daily views, clicks, and traffic source stats',
      reportTrafficCta: 'View report',
      todayTasks: "Today's Tasks",
      todayTasksDesc: "Members' task list & progress for the day",
      todayTasksCta: 'View tasks',
      monthlyReport: 'Monthly Report',
      monthlyReportDesc: 'Monthly performance, traffic, and revenue summary',
      monthlyReportCta: 'View monthly report',
      checklistView: 'Review Reports',
      checklistViewDesc: 'Review reports, checklists, and approvals in the system',
      checklist: 'Checklist',
      checklistDesc: 'Tasks to complete today',
      outstandingApprove: 'Approve Issues & Wins',
      outstandingApproveDesc: 'Approve and record notable issues & daily wins',
      outstanding: 'Issues & Wins',
      outstandingDesc: 'Record notable issues & daily wins',

      myChannels: 'My Channels',
      myChannelsDesc: 'Your social media channels',
      teamChannels: 'Team Channels',
      teamChannelsDesc: "The whole team's social media channels",
      hr: 'HR Management',
      hrDesc: 'Add, edit, and remove team members',

      connectAccounts: 'Connect Accounts',
      connectAccountsDesc: 'Connect Facebook, Instagram, TikTok, Threads, YouTube, Zalo',
      compose: 'Compose & Publish',
      composeDesc: 'Create and publish posts to multiple platforms',
      schedule: 'Post Schedule',
      scheduleDesc: 'Manage automatically scheduled posts',
      monthCalendar: 'Monthly Calendar',
      monthCalendarDesc: 'View scheduled posts in a monthly calendar',
      postHistory: 'Post History',
      postHistoryDesc: 'Track the full history of published posts',
      socialStats: 'Statistics',
      socialStatsDesc: 'Publishing performance charts & analytics',

      channels: 'Channels',
      channelsDesc: 'Manage social media channels',
      channelAnalysis: 'Channel Analytics',
      channelAnalysisDesc: 'In-depth channel data analysis',
      searchHub: 'Video Search (Hub)',
      searchHubDesc: 'Search videos across all platforms',
      collections: 'Collections',
      collectionsDesc: 'Great videos curated by Leaders & Managers for the team',
      translateContent: 'Translate Content',
      translateContentDesc: 'Translate existing content and recheck with a 3-column view',

      taskOverview: 'Overview',
      taskOverviewDesc: 'Task system overview dashboard',
      taskList: 'Task List',
      taskListDesc: 'View and manage all tasks',
      teams: 'Teams',
      teamsDesc: "Manage teams and each team's product & source library",
      catalog: 'Master Catalog',
      catalogDesc: 'System-wide products, content, and sources',
      myCatalog: 'My Library',
      myCatalogDesc: 'Your products, content, and sources',
      kpi: 'KPI',
      kpiDesc: 'Track personal KPI metrics',
      taskSettings: 'Settings',
      taskSettingsDesc: 'Configure automation & task assignment',

      aiOverview: 'Overview',
      aiOverviewDesc: 'View spending, token usage & voice count reports',
      cloneVoice: 'Clone Voice',
      cloneVoiceDesc: 'Clone & generate AI voices from text, translate scripts',

      videoDownloader: 'Social Video Downloader',
      videoDownloaderDesc: 'Download MP4/MP3 from YouTube, TikTok, Facebook... with Chrome extension',

      contentReport: 'Content Report',
      systemSettings: 'System Settings',
      settings: 'Settings',
      logout: 'Log out',
      reportPanelTitle: 'Reports',
      reportPanelDesc: 'Performance reports for Leaders & Members',
      themeToLight: 'Switch to light mode',
      themeToDark: 'Switch to dark mode',

      roleAdmin: 'Administrator',
      roleManager: 'Manager',
      roleLeader: 'Team Leader',
      roleMember: 'Member',
      roleEditor: 'Editor',
      roleContent: 'Content',
    },
  },
} as const;

type NormalizeLeaf<V> = V extends (...args: any[]) => any
  ? V
  : V extends object
  ? Normalize<V>
  : string;

type Normalize<Obj> = { [K in keyof Obj]: NormalizeLeaf<Obj[K]> };

export type SocialT = Normalize<typeof T.vi>;

interface LanguageCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: SocialT;
}

const SocialLanguageContext = createContext<LanguageCtx>({
  lang: 'vi',
  setLang: () => {},
  t: T.vi,
});

export function SocialLanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('vi');

  useEffect(() => {
    try {
      const stored = localStorage.getItem('social_lang') as Lang | null;
      if (stored === 'en' || stored === 'vi') setLangState(stored);
    } catch {}
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    try { localStorage.setItem('social_lang', l); } catch {}
  };

  return (
    <SocialLanguageContext.Provider value={{ lang, setLang, t: T[lang] }}>
      {children}
    </SocialLanguageContext.Provider>
  );
}

export function useSocialLang() {
  return useContext(SocialLanguageContext);
}

// Alias chung cho toàn hệ thống: provider giờ nằm ở root layout, không còn riêng cho Social.
// Code mới nên dùng các tên này; các tên Social* giữ lại để tương thích.
export const LanguageProvider = SocialLanguageProvider;
export const useLang = useSocialLang;
